config/routes.rb
FileUploader::Application.routes.draw do
 
  resources :categories

  resources :images do
    member do
      get "search"
    end
  end
  resources :facebook_uploads

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
    collection do
      get "my_uploads"      
      get "authorize"
      get "dropbox_callback"  
      get "dropbox_download"
    end
  end
  
  resources :statistics ,:only => [:index]do
    
  end
  

  root :to => "publics#index"

end

app/controllers/facebook_uploads_controller.rb
=begin

  @File Name                 : facebook_uploads_controller.rb
  @Company Name              : Mindfire Solutions 
  @Creator Name              : Hare Ram Rai
  @Date Created              : 15-12-2012
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To manage the image upload to facebook

=end

class FacebookUploadsController < ApplicationController
  
  # @Params  : None
  # @Return  : None
  # @Purpose : To display the tag user on the image with comment
  def new
    
    # get the image id from request.env["HTTP_REFERER"]
    @image_id = request.env["HTTP_REFERER"].split("/").last
    
    # fetch the user and its friends details
    facebook_user = FbGraph::User.me(current_user.auth_token).fetch
    @friends = facebook_user.friends   
    
    render :layout => false
    
  end
  
  # @Params  : params
  # @Return  : None
  # @Purpose : To  tag user on the image with comment  and upload it to facebook
  def create
    
    # find the image from the image_id
    @image = Image.find_by_id(params[:image_id])  
    
    # fetch the user details from the facebook
    me = FbGraph::User.me(current_user.auth_token)
    
    #create the array of friends uid
    friends = params[:friends].split(",")
    tags = []
    
    # looping through friends array 
    friends.each do |friend|
      
     #creating a new tag object  and add it to tag array
     tags << FbGraph::Tag.new(
                  :id => friend,
                  :name => "with Facebook profile link",
                  :x => 2*Random.rand(9),
                  :y => 9*Random.rand(2)
      )
      
    end # end of friends block
    
    # uploading the image the friends tag
    FbGraph::User.me(current_user.auth_token).photo!(
      :url => @image.picture.url ,
      :message => params[:message],
      :tags => tags
    )
    
    # create image share record 
    ImageShare.create(:user_id => current_user.id, :image_id => @image.id )
    
    # fetch the new record for images viewed by category
    categories = ImageShare.joins("JOIN images on  image_shares.`image_id` = images.`id` RIGHT JOIN categories on categories.`id` = images.`category_id`").group("categories.id").
     select('categories.title as title,count(image_shares.id) as count').order("categories.title")

    # push the new data to the byimageshared channel        
    PrivatePub.publish_to("/notifications/byimageshared","updateImageShared(#{categories.to_json})")
    
    
    flash[:success] = "Successfully uploaded and tagged the your friends."   
 
    redirect_to image_path(@image)
        
  end # end of create action 
      
end # end of class

app/views/facebook_uploads/new.html.erb
<script type="text/javascript">
  $(document).ready(function () {
    $("#friends").tokenInput([
      <% @friends.each do |friend| %>
              {
                id: <%=  "\'#{friend.raw_attributes[:id]}\'".html_safe%> ,
                name: <%= "\'#{friend.name}\'".html_safe %> ,
                image_url: <%=  "\'http://graph.facebook.com/#{friend.raw_attributes[:id]}/picture\'".html_safe %>
              },
      <% end %>
    ],
    {
      theme: "facebook",
      hintText: "Tag your friends.",
      noResultsText: "O Friends found",
      searchingText: "Searching friends by Name...",
      deleteText: "&#x2603;",
      preventDuplicates: true,
      propertyToSearch: "name",
      minChars: 2,
      tokenLimit: 3,
      resultsFormatter: function(item){ 
        return "<li>" + "<img src='" + item.image_url + "' title='" + item.name+ "' height='25px' width='25px' />" + "<div style='display: inline-block; padding-left: 10px;'><div class='full_name'>" + item.name + "</div></div></li>" 
      },
      tokenFormatter: function(item) { 
        return "<li><p>" + item.name+ "</p></li>" 
      }
    }
   
  );
  
  });  
    
</script>
<div class="form-div">
  <%= form_tag(facebook_uploads_path, :class =>'form-horizontal' ) do -%>

    <%= field_set_tag 'Tags your friends' do %>

      <div class="control-group">
        <%=  label_tag :friends, nil, :class => 'control-label' %>
        <div class="controls">
          <%= text_field_tag :friends, nil, :class => 'check_box' %>
        </div>
        <%= hidden_field_tag :image_id , @image_id %>
      </div>
      <div class="control-group">
        <%=  label_tag :message, nil, :class => 'control-label' %>
        <div class="controls">
          <%= text_area_tag :message, nil,:class => 'text-area'%>
        </div>        
      </div>

      <div class="form-actions">
        <%= submit_tag nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
          images_path, :class => 'btn' %>
      </div>

    <% end %>

  <% end %>

</div>