config/routes.rb
FileUploader::Application.routes.draw do
 
  resources :categories

  resources :images do
    member do
      get "search"
    end
  end
  resources :facebook_uploads

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
    collection do
      get "my_uploads"      
      get "authorize"
      get "dropbox_callback"  
      get "dropbox_download"
    end
  end
  
  resources :statistics ,:only => [:index]do
    
  end
  

  root :to => "publics#index"

end

app/models/image.rb
=begin

  @File Name                 : image.rb
  @Company Name              : Mindfire Solutions
  @Creator Name              : Hare Ram Rai
  @Date Created              : 15-12-2012
  @Date Modified             : 10-01-12013
  @Last Modification Details : added association
  @Purpose                   : To manage the image model

=end
class Image < ActiveRecord::Base  
  
  attr_accessible :picture, :verified, :category, :tags, :user_id, :category_id
    
  has_attached_file :picture,
    :storage => :dropbox,
    :dropbox_credentials => "#{Rails.root}/config/dropbox.yml",
    :styles => { :medium => "300x300" , :thumb => "100x100>"},
    :dropbox_options => {
      :path => proc { |style| "#{style}/#{id}_#{picture.original_filename}"},
      :unique_filename => true
    }

######################################################################################################################
#           VALIDATION STARTS HERE                                                                                   #
######################################################################################################################

    validates :picture, :attachment_presence => true
    validates :tags, :presence =>true
    validates :category, :presence => true
   
######################################################################################################################
#            VALIDATION ENDS HERE                                                                                    #
######################################################################################################################
 
##########################
#Defining Associations   #
##########################

  belongs_to :user
  belongs_to :category
  has_many :image_downloads
  has_many :image_views
  has_many :image_shares  

##########################
#End Defining Associations
##########################  
   
end # end of class

app/models/image_view.rb
=begin

  @File Name                 : image_view.rb
  @Company Name              : Mindfire Solutions
  @Creator Name              : Hare Ram Rai
  @Date Created              : 10-01-2013
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To manage the image view  model

=end
class ImageView < ActiveRecord::Base
  
  # attribute accessible fields are
  attr_accessible :image_id, :user_id, :created_at, :id
  
  ##########################
  #Defining Associations   #
  ##########################
  
    belongs_to :user
    belongs_to :image
    
  ##########################
  #End Defining Associations
  ##########################  
  
end

app/controllers/images_controller.rb
=begin

  @File Name                 : images_controller.rb
  @Company Name              : Mindfire Solutions 
  @Creator Name              : Hare Ram Rai
  @Date Created              : 15-12-2012
  @Date Modified             :
  @Last Modification Details :
  @Purpose                   : To manage the images

=end

class ImagesController < ApplicationController
  
  # for user authentication 
  before_filter :authenticate_user!, :except => [:index,:search]
  #load_and_authorize_resource
  load_and_authorize_resource :except => [:search]

  
  # @Params  : None
  # @Return  : None
  # @Purpose : To display all the images
  def index
    
    #fetch the all images
    @images = Image.includes(:category).all
    @images.created_at

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @images }      
    end
    
  end # end of index action

 
  # @Params  : params[:id]
  # @Return  : None
  # @Purpose : To show the a image   
  def show
    
    # find the image by id
    @image = Image.find(params[:id])
    ImageView.find_or_create_by_user_id_and_image_id(current_user.id,@image.id)
    
    # fetch the new record for images viewed by category 
    categories = ImageView.joins("JOIN images on  image_views.`image_id` = images.`id` RIGHT JOIN categories on categories.`id` = images.`category_id`").
    group("categories.id").select('categories.title as title,count(image_views.id) as count').order("categories.title")
        
    # push the new data to the byimageviewed channel    
    PrivatePub.publish_to("/notifications/byimageviewed","updateImageViewed(#{categories.to_json})")
          
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @image }
    end
    
  end # end of show action

  
  # @Params  : None
  # @Return  : None
  # @Purpose : To display a form for creating image
  def new
    
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @image }
    end
    
  end # end of new action
  
  # @Params  : params[:id]
  # @Return  : None
  # @Purpose : To edit the image
  def edit
    
    @image = Image.find(params[:id])
    
  end # end of edit action

  
  # @Params  : params[:image]
  # @Return  : None
  # @Purpose : To create the new image object
  def create
    
    # create the image with params[:image]
    @image = Image.new(params[:image])
    
    #set the user_id of image with current user id
    @image.user_id = current_user.id
    
    respond_to do |format|
      if @image.save
        
        categories = Category.joins("LEFT OUTER JOIN images on categories.`id` = images.`category_id`").group("categories.id").select('categories.title,count(images.category_id) as count') 
        PrivatePub.publish_to("/notifications/bycategory","updateImageCreated(#{categories.to_json})")
    
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render json: @image, status: :created, location: @image }
      else
        format.html { render action: "new" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
    
  end # end of create action

 
  # @Params  : params[:id]
  # @Return  : None
  # @Purpose : To update the image object
  def update
    
    # find the image with params[:id]
    @image = Image.find(params[:id])
    
    #set the user_id of image with current user id
    @image.user_id = current_user.id
    
    respond_to do |format|
      
      if @image.update_attributes(params[:image])
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
      
    end
    
  end # end of update action

 
  # @Params  : params[:id]
  # @Return  : None
  # @Purpose : To delete the image 
  def destroy
    
    # find the image with params[:id]
    @image = Image.find(params[:id])
    
    #delete the image
    @image.destroy

    respond_to do |format|
      
      format.html { redirect_to images_url }
      format.json { head :no_content }
      
    end
    
  end # end of destroy action

  # @Params  : None
  # @Return  : None
  # @Purpose : To search the image based on key or category
  def search
    
    if params[:id] == "search"
      
      # find the related image to params[:key]
      @images = Image.where("tags LIKE ? OR  picture_file_name LIKE ?", "%#{params[:key]}%", "%#{params[:key]}%")      
      
    else
      
      # find the image by category 
      @images = Image.where("category_id = ?",params[:id])      
      
    end
    
    respond_to do |format|
      
      format.html { render "index"}
      format.json { render json: @images }
      
    end
    
  end # end of search action
  
end # end of class

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html => { :class => 'form-horizontal' } do |f| %>
<%= display_base_errors @image %>  
<div class="control-group">
    <%= f.label :picture, :class => 'control-label' %>
    <div class="controls">
      <div class="fileupload fileupload-new" data-provides="fileupload">
        <div class="fileupload-preview thumbnail" style="width: 200px; height: 150px;">
          
        </div>
        <div>
          <span class="btn btn-file">
            <span class="fileupload-new">Select image</span>
            <span class="fileupload-exists">Change</span>            
              <%= f.file_field :picture, :class => 'file_field' %>
            </span>
            <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
        </div>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :verified, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :verified, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_id,@categories.collect {|category| [ category.title, category.id ] }, :class => 'select_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :tags, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tags, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                images_path, :class => 'btn' %>
  </div>
<% end %>

app/views/images/edit.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/index.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:picture_content_type) %></th>      
      <th><%= model_class.human_attribute_name(:verified) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>      
      <th><%= model_class.human_attribute_name(:created_at) %></th> 
      <% if can? :create, Image %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%  if @images.blank?%>
      <tr><td colspan="7" class="table-no-record">      No images found   </td> </tr>
    <% else %>
      <% @images.each do |image| %>
        <tr>
          <td><%= link_to image.id, image_path(image) %></td>
          <td><%= link_to (image_tag  image.picture.url(:thumb,:download => true)), image_path(image)  %></td>
          <td><%= image.picture_content_type %></td>        
          <td><%= image.verified %></td>
          <td><%= image.category.title %></td>
          <td><%= image.tags %></td>
          <td><%=l image.created_at %></td>
          <% if can? :create, Image %>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_image_path(image), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                image_path(image),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-mini btn-danger' %>
            </td>
          <% end %>
        </tr>
      <% end %>

    <% end %>
  </tbody>
</table>
<% if can? :create, Image %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
    new_image_path,
    :class => 'btn btn-primary' %>
<% end %>

app/views/images/new.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/images/show.html.erb
<%- model_class = Image -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%=image_tag @image.picture.url(:medium,:download => true) %></dd> 
  <dt><strong><%= model_class.human_attribute_name(:picture_content_type) %>:</strong></dt>
  <dd><%= @image.picture_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture_file_size) %>:</strong></dt>
  <dd><%= @image.picture_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture_updated_at) %>:</strong></dt>
  <dd><%= @image.picture_updated_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:verified) %>:</strong></dt>
  <dd><%= @image.verified %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @image.category.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tags) %>:</strong></dt>
  <dd><%= @image.tags %></dd>
</dl>

<div class="form-actions">
  <% if current_user.dropbox_session.blank? %>
  <%= link_to "Authorize Dropbox",authorize_users_path ,:class => 'btn btn-primary'   %>
  <% else %>
  <%= link_to "Download Dropbox",dropbox_download_users_path ,:class => 'btn btn-primary'   %>
  <% end %>
  
  <%= link_to "Upload to Facebook",new_facebook_upload_path, :class => 'btn btn-primary color-box-ajax'  %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              images_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_image_path(@image), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              image_path(@image),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>