config/routes.rb
FileUploader::Application.routes.draw do
 
  resources :categories

  resources :images do
    member do
      get "search"
    end
  end
  resources :facebook_uploads

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
    collection do
      get "my_uploads"      
      get "authorize"
      get "dropbox_callback"  
      get "dropbox_download"
    end
  end
  
  resources :statistics ,:only => [:index]do
    
  end
  

  root :to => "publics#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Picture Sharing" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "private_pub"%>    
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">FileUploader</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Pictures",images_path  %></li>
              <% if can? :create, Image %>
                <li><%= link_to "Upload Picture", new_image_path  %></li>
              <% end %>   
              <% if can? :my_uploads, User %>
                <li><%= link_to "My Uploads", my_uploads_users_path  %></li>
              <% end %>  
              <li><%= link_to "Image Statistics", statistics_path  %> </li>
              <li>
                <form class="navbar-search pull-left" action="/images/search/search">
                  <input type="text" name="key" class="search-query" placeholder="Search">
                </form>
              </li>
            </ul>

            <ul class="nav pull-right">

              <% if user_signed_in?  %>
                <li><%= image_tag current_user.facebook_image , :class => "user-min-image" %></li>
                <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <%= current_user.name %><b class="caret"></b>
                  </a> 
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "Sign out", destroy_user_session_path, :method => :delete  %>
                    </li> 
                    <li class="divider"></li>
                    <li class="nav-header">Profile Settings</li>
                    <li>
                      <%= link_to "Profile",user_path(current_user) %>
                    </li>                    
                  </ul>
                </li>
                <li>                 

                </li>

              <% else %>

                <li><%= link_to "",user_omniauth_authorize_path(:facebook),:class => "facebook"%></li>

              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= render :partial => "shared/flash_messages" %>
        <div class="span9">            
          <%= yield %>
        </div>
        <div class="span3">
          <div class="well sidebar-nav">
            <h3>Category </h3>
            <ul class="nav nav-list">
              <li class="nav-header">Photo By Category</li>
              <% @categories.each do |category| %>
              <li><%= link_to "#{category.title} (#{category.images.size})", search_image_path(category)  %></li>
              <% end %>              
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <div class="container">
        <p class="muted credit">
          Simple image sharing web application by <a href="https://facebook.com/java.hareram">Hare Ram Rai</a>
        </p>   
        </div>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application",params[:controller] %>

  </body>
</html>